# Generated by Django 6.0.6 on 2026-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this instead of deleting the product to pull it off the frontend shop layout.'),
        ),
    ]
